spring.datasource.url=jdbc:postgresql://dpg-d8s9os37uimc73845jp0-a:5432/shopmemo_db
spring.datasource.username=shopmemo_db_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver